import { relations, sql } from 'drizzle-orm';
import { index, pgEnum, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { USER_ROLES } from '../../domain/user-role.js';

/*
 * Identity tables (drizzle-kit reads this file: ONLY drizzle-orm imports + dependency-free
 * relative files — see blueprint §3.6). Column names come from `casing: 'snake_case'`.
 *
 * Ids are uuidv7 generated by the application (known before INSERT: domain events, the session
 * id doubles as the refresh token `jti`). The Postgres 18 `uuidv7()` DEFAULT only covers raw SQL
 * inserts (seeds, psql). uuidv7 is time-ordered, so `ORDER BY id DESC` = newest first and the PK
 * index serves keyset pagination (scanned backwards — no extra index needed).
 *
 * Search: `ILIKE '%q%'` on email/display_name cannot use a btree, so `users_search_trgm_idx` is a
 * pg_trgm GIN index on both columns (the `OR` becomes a BitmapOr). Trigrams need >= 3 characters,
 * hence `IDENTITY_LIMITS.SEARCH_MIN_LENGTH`. The migration that creates it starts with
 * `CREATE EXTENSION IF NOT EXISTS pg_trgm` (hand-added: drizzle-kit does not emit extensions;
 * pg_trgm is a trusted extension, so the database owner may create it).
 */

const timestamptz = () => timestamp({ withTimezone: true, precision: 3, mode: 'date' });

/** RBAC roles (values = @app/auth `Role`). */
export const userRole = pgEnum('user_role', USER_ROLES);

export const users = pgTable(
  'users',
  {
    id: uuid().primaryKey().default(sql`uuidv7()`),
    /** Normalised (trimmed + lowercase) before it gets here, so a plain unique constraint is enough. */
    email: text().notNull().unique('users_email_unique'),
    passwordHash: text().notNull(),
    displayName: text().notNull(),
    roles: userRole().array().notNull().default(sql`ARRAY['user']::user_role[]`),
    createdAt: timestamptz().notNull().defaultNow(),
    updatedAt: timestamptz()
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    // admin user search: `email ILIKE '%q%' OR display_name ILIKE '%q%'`.
    index('users_search_trgm_idx').using(
      'gin',
      t.email.op('gin_trgm_ops'),
      t.displayName.op('gin_trgm_ops'),
    ),
  ],
);

export const sessions = pgTable(
  'sessions',
  {
    /** = the refresh token's `jti`. */
    id: uuid().primaryKey(),
    userId: uuid()
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** sha256 hex of the refresh token (never the token itself). */
    refreshTokenHash: text().notNull(),
    userAgent: text(),
    ip: text(),
    expiresAt: timestamptz().notNull(),
    revokedAt: timestamptz(),
    replacedById: uuid(),
    createdAt: timestamptz().notNull().defaultNow(),
  },
  (t) => [
    // "revoke all sessions of a user" (reuse detection, sign-out everywhere) + FK cascade.
    index('sessions_user_id_idx').on(t.userId),
    // hourly purge `WHERE expires_at <= now()`.
    index('sessions_expires_at_idx').on(t.expiresAt),
  ],
);

export const usersRelations = relations(users, ({ many }) => ({
  sessions: many(sessions),
}));

export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(users, { fields: [sessions.userId], references: [users.id] }),
}));

/**
 * Everything `DatabaseModule.forRootAsync({ schema })` needs for this context. The monolith
 * spreads it with the other contexts: `{ ...identitySchema, ...billingSchema }` (keys are unique).
 */
export const identitySchema = {
  userRole,
  users,
  sessions,
  usersRelations,
  sessionsRelations,
};

export type IdentitySchema = typeof identitySchema;
export type UserRow = typeof users.$inferSelect;
export type NewUserRow = typeof users.$inferInsert;
export type SessionRow = typeof sessions.$inferSelect;
export type NewSessionRow = typeof sessions.$inferInsert;
