import { generateId, normalizeEmail, type ValidationIssue } from '@app/common';
import { AggregateRoot } from '@nestjs/cqrs';
import { isEmpty, isEqual, sortBy, uniq } from 'lodash-es';
import { IDENTITY_LIMITS } from '../identity.constants.js';
import { UserRegisteredEvent } from './events/user-registered.event.js';
import { UserRolesChangedEvent } from './events/user-roles-changed.event.js';
import {
  CannotRevokeOwnAdminRoleException,
  InvalidRolesException,
  InvalidUserException,
} from './identity.errors.js';
import {
  ADMIN_ROLE,
  DEFAULT_USER_ROLE,
  isUserRole,
  USER_ROLES,
  type UserRole,
} from './user-role.js';

/** The persisted state of a user (what repositories load and save). */
export interface UserSnapshot {
  readonly id: string;
  /** Normalised: trimmed + lowercase (the unique key). */
  readonly email: string;
  readonly displayName: string;
  /** Argon2id PHC string. Never leaves the identity service. */
  readonly passwordHash: string;
  /** Deduplicated, in canonical `USER_ROLES` order. */
  readonly roles: readonly UserRole[];
  readonly createdAt: Date;
  readonly updatedAt: Date;
}

export interface RegisterUserProps {
  /** uuidv7, generated by the caller so the id is known before INSERT (events, session FK). */
  id: string;
  email: string;
  displayName: string;
  passwordHash: string;
  now: Date;
}

/** Canonical role list: unique, ordered like `USER_ROLES` (stable equality, stable storage). */
function canonicalRoles(roles: readonly UserRole[]): UserRole[] {
  return sortBy(uniq(roles), (role) => USER_ROLES.indexOf(role));
}

/**
 * User aggregate: registration and role management invariants. Pure domain logic — persistence
 * happens in `UsersRepository`, and the events applied here are published (via the CQRS
 * `EventPublisher`) only after the handler's transaction committed.
 */
export class UserAggregate extends AggregateRoot {
  private state: UserSnapshot;

  private constructor(state: UserSnapshot) {
    super();
    this.state = state;
  }

  /** A new account with the default role; applies `UserRegisteredEvent`. */
  static register(props: RegisterUserProps): UserAggregate {
    const email = normalizeEmail(props.email);
    const displayName = props.displayName.trim();
    const issues: ValidationIssue[] = [];
    if (!email.includes('@') || email.length > IDENTITY_LIMITS.EMAIL_MAX_LENGTH) {
      issues.push({ path: 'email', message: 'Must be a valid email address' });
    }
    if (
      displayName.length < IDENTITY_LIMITS.DISPLAY_NAME_MIN_LENGTH ||
      displayName.length > IDENTITY_LIMITS.DISPLAY_NAME_MAX_LENGTH
    ) {
      issues.push({
        path: 'displayName',
        message: `Must be ${IDENTITY_LIMITS.DISPLAY_NAME_MIN_LENGTH}-${IDENTITY_LIMITS.DISPLAY_NAME_MAX_LENGTH} characters`,
      });
    }
    if (isEmpty(props.passwordHash)) {
      issues.push({ path: 'passwordHash', message: 'Must not be empty' });
    }
    if (issues.length > 0) throw new InvalidUserException(issues);

    const user = new UserAggregate({
      id: props.id,
      email,
      displayName,
      passwordHash: props.passwordHash,
      roles: [DEFAULT_USER_ROLE],
      createdAt: props.now,
      updatedAt: props.now,
    });
    user.apply(new UserRegisteredEvent(generateId(), props.id, email, displayName, props.now));
    return user;
  }

  /** Rehydrates a persisted user (no events). */
  static restore(snapshot: UserSnapshot): UserAggregate {
    return new UserAggregate({ ...snapshot, roles: canonicalRoles(snapshot.roles) });
  }

  get id(): string {
    return this.state.id;
  }

  get roles(): readonly UserRole[] {
    return this.state.roles;
  }

  hasRole(role: UserRole): boolean {
    return this.state.roles.includes(role);
  }

  /**
   * Replaces the role set. Returns `false` (and applies nothing) when the set is unchanged.
   * @throws InvalidRolesException empty list or unknown role names
   * @throws CannotRevokeOwnAdminRoleException the actor is this admin and drops `admin`
   */
  changeRoles(roles: readonly string[], actorId: string, now: Date): boolean {
    const unknown = roles.filter((role) => !isUserRole(role));
    if (roles.length === 0 || unknown.length > 0) {
      throw new InvalidRolesException(
        roles.length === 0
          ? [{ path: 'roles', message: 'At least one role is required' }]
          : unknown.map((role) => ({
              path: 'roles',
              message: `Unknown role "${role}" (allowed: ${USER_ROLES.join(', ')})`,
            })),
      );
    }
    const next = canonicalRoles(roles.filter(isUserRole));
    if (actorId === this.state.id && this.hasRole(ADMIN_ROLE) && !next.includes(ADMIN_ROLE)) {
      throw new CannotRevokeOwnAdminRoleException();
    }
    if (isEqual(next, this.state.roles)) return false;

    const previous = this.state.roles;
    this.state = { ...this.state, roles: next, updatedAt: now };
    this.apply(
      new UserRolesChangedEvent(generateId(), this.state.id, previous, next, actorId, now),
    );
    return true;
  }

  toSnapshot(): UserSnapshot {
    return { ...this.state, roles: [...this.state.roles] };
  }
}
